<?php

namespace PnX\TaxonomieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VTaxrefHierarchieBibtaxonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VTaxrefHierarchieBibtaxonsRepository extends EntityRepository
{
    public function findLimitedTaxrefHierarchieBibtaxons($limit = 50 , $where, $qparameters, $join) {
        $fieldListeQry = $this->createQueryBuilder('VTaxrefHierarchieBibtaxons')
            ->setMaxResults($limit);
            
        if (count($where)>0) {
            $fieldListeQry = $fieldListeQry->where(implode(" AND ", $where))->setParameters($qparameters);
        }    
        if (count($join)>0) {
            $fieldListeQry = $fieldListeQry->join('VTaxrefHierarchieBibtaxons.BibTaxons', 't');
        }
        
        $results= $fieldListeQry->getQuery()->getResult();
        
        return $results;
    }
}
