SQLALCHEMY_DATABASE_URI = "postgresql://taxhubadmin:taxhubpwd@127.0.0.1:5432/taxhub"
SECRET_KEY = 'a7e0a755dd3f2c382bac5b5cea6c9329802aeedf39e3f10d0462ffb52c3f5e99'

# Custom media config folder for s3
MEDIA_FOLDER = "custom_media" 
MEDIA_SUBFOLDER = "sub_medias" 
THUMB_SUBFOLDER= "sub_thumb" 