TAXREF_DETAILS_PARENTS = [
    {
        "cd_nom": 67111,
        "linnaean": True,
        "parents": [
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
            {"cd_ref": 185704, "id_rang": "CL", "lb_nom": "Actinopterygii"},
            {"cd_ref": 419279, "id_rang": "OR", "lb_nom": "Cypriniformes"},
            {"cd_ref": 905695, "id_rang": "FM", "lb_nom": "Leuciscidae"},
            {"cd_ref": 188935, "id_rang": "GN", "lb_nom": "Alburnus"},
        ],
    },
    {
        "cd_nom": 67111,
        "linnaean": False,
        "parents": [
            {"cd_ref": 349525, "id_rang": "Dumm", "lb_nom": "Biota"},
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 838319, "id_rang": "SSRG", "lb_nom": "Eumetazoa"},
            {"cd_ref": 838322, "id_rang": "IFRG", "lb_nom": "Deuterostomia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
            {"cd_ref": 838103, "id_rang": "SBPH", "lb_nom": "Craniata"},
            {"cd_ref": 185695, "id_rang": "IFPH", "lb_nom": "Vertebrata"},
            {"cd_ref": 185703, "id_rang": "SPCL", "lb_nom": "Gnathostomata"},
            {"cd_ref": 838092, "id_rang": "CLAD", "lb_nom": "Euteleostomi"},
            {"cd_ref": 838320, "id_rang": "CLAD", "lb_nom": "Bilateria"},
            {"cd_ref": 185704, "id_rang": "CL", "lb_nom": "Actinopterygii"},
            {"cd_ref": 838106, "id_rang": "SBCL", "lb_nom": "Neopterygii"},
            {"cd_ref": 185709, "id_rang": "IFCL", "lb_nom": "Teleostei"},
            {"cd_ref": 419279, "id_rang": "OR", "lb_nom": "Cypriniformes"},
            {"cd_ref": 903695, "id_rang": "SBOR", "lb_nom": "Cyprinoidei"},
            {"cd_ref": 905695, "id_rang": "FM", "lb_nom": "Leuciscidae"},
            {"cd_ref": 825329, "id_rang": "SBFM", "lb_nom": "Leuciscinae"},
            {"cd_ref": 188935, "id_rang": "GN", "lb_nom": "Alburnus"},
        ],
    },
    {
        "cd_nom": 905695,
        "linnaean": True,
        "parents": [
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
            {"cd_ref": 185704, "id_rang": "CL", "lb_nom": "Actinopterygii"},
            {"cd_ref": 419279, "id_rang": "OR", "lb_nom": "Cypriniformes"},
        ],
    },
    {
        "cd_nom": 905695,
        "linnaean": False,
        "parents": [
            {"cd_ref": 349525, "id_rang": "Dumm", "lb_nom": "Biota"},
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 838319, "id_rang": "SSRG", "lb_nom": "Eumetazoa"},
            {"cd_ref": 838322, "id_rang": "IFRG", "lb_nom": "Deuterostomia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
            {"cd_ref": 838103, "id_rang": "SBPH", "lb_nom": "Craniata"},
            {"cd_ref": 185695, "id_rang": "IFPH", "lb_nom": "Vertebrata"},
            {"cd_ref": 185703, "id_rang": "SPCL", "lb_nom": "Gnathostomata"},
            {"cd_ref": 838320, "id_rang": "CLAD", "lb_nom": "Bilateria"},
            {"cd_ref": 838092, "id_rang": "CLAD", "lb_nom": "Euteleostomi"},
            {"cd_ref": 185704, "id_rang": "CL", "lb_nom": "Actinopterygii"},
            {"cd_ref": 838106, "id_rang": "SBCL", "lb_nom": "Neopterygii"},
            {"cd_ref": 185709, "id_rang": "IFCL", "lb_nom": "Teleostei"},
            {"cd_ref": 419279, "id_rang": "OR", "lb_nom": "Cypriniformes"},
            {"cd_ref": 903695, "id_rang": "SBOR", "lb_nom": "Cyprinoidei"},
        ],
    },
    {
        "cd_nom": 185704,
        "linnaean": True,
        "parents": [
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
        ],
    },
    {
        "cd_nom": 185704,
        "linnaean": False,
        "parents": [
            {"cd_ref": 349525, "id_rang": "Dumm", "lb_nom": "Biota"},
            {"cd_ref": 183716, "id_rang": "KD", "lb_nom": "Animalia"},
            {"cd_ref": 838319, "id_rang": "SSRG", "lb_nom": "Eumetazoa"},
            {"cd_ref": 838322, "id_rang": "IFRG", "lb_nom": "Deuterostomia"},
            {"cd_ref": 185694, "id_rang": "PH", "lb_nom": "Chordata"},
            {"cd_ref": 838103, "id_rang": "SBPH", "lb_nom": "Craniata"},
            {"cd_ref": 185695, "id_rang": "IFPH", "lb_nom": "Vertebrata"},
            {"cd_ref": 185703, "id_rang": "SPCL", "lb_nom": "Gnathostomata"},
            {"cd_ref": 838092, "id_rang": "CLAD", "lb_nom": "Euteleostomi"},
            {"cd_ref": 838320, "id_rang": "CLAD", "lb_nom": "Bilateria"},
        ],
    },
]
